jobs:
  include:
    - language: node_js
      node_js:
        - 12
      install:
        - yarn
      script:
        - yarn test

    - language: android
      jdk: oraclejdk8
      env:
        - ANDROID_API=28
        - ANDROID_BUILD_TOOLS=28.0.3
      android:
        components:
          - tools
          - platform-tools
          - android-${ANDROID_API}
          - build-tools-${ANDROID_BUILD_TOOLS}
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        yarn: true
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - Example/node_modules
      install: true
      script:
        - ./.travis/example/install.android.sh

    - language: objective-c
      osx_image: xcode10.2
      xcode_sdk: iphonesimulator12.2
      xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone X
      env:
        - PRODUCT_BUNDLE_IDENTIFIER='org.reactjs.native.example.ReanimatedExample'
      branches:
        only:
          - master
      cache:
        yarn: true
        directories:
          - Example/ios/Pods
          - Example/node_modules
      install: true
      script:
        - ./.travis/example/install.ios.sh

    - language: android
      jdk: oraclejdk8
      env:
        - ANDROID_API=28
        - ANDROID_BUILD_TOOLS=28.0.3
      android:
        components:
          - tools
          - platform-tools
          - android-${ANDROID_API}
          - build-tools-${ANDROID_BUILD_TOOLS}
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        yarn: true
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - Example/node_modules
      install:
        - ./.travis/e2e/install.android.sh
      script:
        - yarn run test-android

    - language: objective-c
      osx_image: xcode10.2
      xcode_sdk: iphonesimulator12.2
      xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone X
      env:
        - PRODUCT_BUNDLE_IDENTIFIER='org.reactjs.native.example.ReanimatedExample'
      branches:
        only:
          - master
      cache:
        yarn: true
        directories:
          - Example/ios/Pods
          - Example/node_modules
      install:
        - ./.travis/e2e/install.ios.sh
      script:
        - yarn run test-ios
