language: node_js
node_js: 12
env:
  - NODE_VERSION=13.3.0
jobs:
  include:
    - language: node_js
      node_js: 12
      install:
        - yarn
      script:
        - yarn test

    - language: android
      jdk: oraclejdk8
      env:
        - ANDROID_API=28
        - ANDROID_BUILD_TOOLS=28.0.3
        - NODE_VERSION=13.3.0
      android:
        components:
          - tools
          - platform-tools
          - android-${ANDROID_API}
          - build-tools-${ANDROID_BUILD_TOOLS}
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        yarn: true
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - Example/node_modules
      install:
        - nvm install $NODE_VERSION
        - nvm use $NODE_VERSION
        - nvm alias default $NODE_VERSION
        - node --version
        - npm install -g react-native-cli detox-cli yarn
        - yarn

        - cd Example
        - yarn
      script:
        - cd ./android && ./gradlew assembleDebug

    - language: objective-c
      osx_image: xcode11.2
      xcode_sdk: iphonesimulator12.2
      xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone X
      env:
        - PRODUCT_BUNDLE_IDENTIFIER='org.reactjs.native.example.ReanimatedExample'
        - CODE_SIGNING_REQUIRED=NO
        - NODE_VERSION=13.3.0
      branches:
        only:
          - master
      cache:
        yarn: true
        directories:
          - Example/ios/Pods
          - Example/node_modules
      install:
        - nvm install $NODE_VERSION
        - nvm use $NODE_VERSION
        - nvm alias default $NODE_VERSION
        - node --version
        - npm install -g react-native-cli detox-cli yarn
        - yarn

        - cd Example
        - HOMEBREW_NO_INSTALL_CLEANUP=1 HOMEBREW_NO_AUTO_UPDATE=1 brew tap wix/brew
        - HOMEBREW_NO_INSTALL_CLEANUP=1 HOMEBREW_NO_AUTO_UPDATE=1 brew install applesimutils
        - sudo ulimit -n 10000
        - sudo launchctl limit maxfiles 2048 unlimited
        - yarn
        - cd ios && pod install && cd ..
      script:
        - xcodebuild -workspace ./ios/ReanimatedExample.xcworkspace -scheme ReanimatedExample -configuration Debug -sdk iphonesimulator -derivedDataPath ./ios/build -UseModernBuildSystem=NO

    - language: android
      jdk: oraclejdk8
      env:
        - ANDROID_API=28
        - ANDROID_BUILD_TOOLS=28.0.3
        - NODE_VERSION=13.3.0
      android:
        components:
          - tools
          - platform-tools
          - android-${ANDROID_API}
          - build-tools-${ANDROID_BUILD_TOOLS}
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        yarn: true
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - Example/node_modules
      install:
        - nvm install $NODE_VERSION
        - nvm use $NODE_VERSION
        - nvm alias default $NODE_VERSION
        - node --version
        - npm install -g react-native-cli detox-cli yarn
        - yarn

        - cd e2e
        - yarn
        - cd ./android && ./gradlew assembleDebug
      script:
        - yarn run test-android

    - language: objective-c
      osx_image: xcode11.2
      xcode_sdk: iphonesimulator12.2
      xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone X
      env:
        - PRODUCT_BUNDLE_IDENTIFIER='org.reactjs.native.e2e'
        - CODE_SIGNING_REQUIRED=NO
        - NODE_VERSION=13.3.0
      branches:
        only:
          - master
      cache:
        yarn: true
        directories:
          - Example/ios/Pods
          - Example/node_modules
      install:
        - nvm install $NODE_VERSION
        - nvm use $NODE_VERSION
        - nvm alias default $NODE_VERSION
        - node --version
        - npm install -g react-native-cli detox-cli yarn
        - yarn

        - HOMEBREW_NO_INSTALL_CLEANUP=1 HOMEBREW_NO_AUTO_UPDATE=1 brew tap wix/brew
        - HOMEBREW_NO_INSTALL_CLEANUP=1 HOMEBREW_NO_AUTO_UPDATE=1 brew install applesimutils
        - sudo ulimit -n 10000
        - sudo launchctl limit maxfiles 2048 unlimited
        - yarn
        - cd ios && pod install && cd ..
        - xcodebuild -workspace ios/e2e.xcworkspace -scheme e2e -configuration Debug -sdk iphonesimulator -derivedDataPath ./ios/build -UseModernBuildSystem=NO
      script:
        - yarn run test-ios
