jobs:
  include:
    - stage: Prepare environment
      env:
        - NODE_VERSION=13.3.0
      cache:
        - yarn
        - directories:
            - node_modules
      install:
        - nvm --version
        - echo $NODE_VERSION
        - sudo ulimit -n 10000
        - nvm install $NODE_VERSION
        - nvm use $NODE_VERSION
        - nvm alias default $NODE_VERSION
        - brew install yarn --ignore-dependencies
        - npm install -g react-native-cli
      script: yarn

    - stage: Build
      language: node_js
      node_js: 13
      script:
        - yarn test

    - stage: Build
      language: android
      jdk: oraclejdk8
      env:
        - ANDROID_API=28
        - ANDROID_BUILD_TOOLS=28.0.3
      android:
        components:
          - tools
          - platform-tools
          - android-${ANDROID_API}
          - build-tools-${ANDROID_BUILD_TOOLS}
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - Example/node_modules
      install:
        - cd Example
        - yarn
      script:
        - cd ./android && ./gradlew assembleDebug

    - stage: Build
      language: objective-c
      osx_image: xcode10.2
      xcode_sdk: iphonesimulator12.2
      xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone X
      env:
        - PRODUCT_BUNDLE_IDENTIFIER='org.reactjs.native.example.ReanimatedExample'
      branches:
        only:
          - master
      cache:
        directories:
          - Example/ios/Pods
      install:
        - sudo launchctl limit maxfiles 2048 unlimited
        - cd Example
        - yarn
        - cd ios && pod install && cd ..
      script:
        - xcodebuild -workspace ./ios/ReanimatedExample.xcworkspace -scheme ReanimatedExample -configuration Debug -sdk iphonesimulator -derivedDataPath ./ios/build -UseModernBuildSystem=NO
